application: trackme-web
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:  
  
- url: /res
  static_dir: resource
  
- url: /mapi/.*
  script: mapi.application

- url: /.*
  script: trackme.application

# [START libraries]
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
# [END libraries]